services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false
        
    Kematjaya\SaleBundle\Service\SaleServiceInterface:
        class: Kematjaya\SaleBundle\Service\SaleService